### ISSUE TITLE
[BUG]: Cant change number of sample steps

### ISSUE THREAD

**Issue by JSarvise** [demibit/stable-toolkit#11]
It's stuck at 20 sample steps which only makes the image done like that available to appear and be filtered
![imagen](https://user-images.githubusercontent.com/63007850/196300002-951f5a6c-6a93-4765-82ea-796b87ad180d.png)

**Comment by demibit** [comment]
Do you have images that have sample steps above 20?

**Comment by JSarvise** [comment]
Yup, but no idea why i can only tweak denoise and cfg

**Comment by demibit** [comment]
It picks up the minimum and maximum possible values based on your images' properties. So it wouldn't make sense to search images above 20 sample steps when there are none. Do you see this otherwise?

**Comment by JSarvise** [comment]
Thats the thing i have created multiple images with different sample steps lets say for example the max should be 28, why is ot only 20-20 showing. Is it because im using a different output folder that the default ones the web ui has?

**Comment by demibit** [comment]
Right, I see. Some questions
- Have you tried the troubleshooting steps in the README?
- Do these images (with higher step count for example) appear in the toolkit's UI?
- If yes, are their generation parameters indexed? (If you click on it it should show up in the 3rd box on the right)

The service looks for min/max values throughout every image in the db regardless of folder, so where they come from should not matter.

**Comment by demibit** [comment]
Stale, closing
