### ISSUE TITLE
Changing MongoDB host

### ISSUE THREAD

**Issue by giubil** [demibit/stable-toolkit#15]
Hello, 

I'm currently in the process of creating a Docker configuration (as to enable Linux support), and for it to run I need the Spring app to connect to a MongoDB instance on a different host than `localhost`, such as `mongodb` or `10.X.X.X`. 

I'm not that hugely familiar with Java, so I was wondering on what would be the best way to accomplish that.

Also, once I get the Docker config up and running I'm planning on opening a PR for it.

Thanks

**Comment by demibit** [comment]
I believe this is what you're looking for (stable-toolkit-back\src\main\resources\application.properties). Docker would be nice

![m1](https://user-images.githubusercontent.com/17875309/196688896-9f0385aa-62c9-4b3e-9fc9-4529e012f8dc.png)

**Comment by demibit** [comment]
Stale, closing
