### ISSUE TITLE
[FEATURE]: Open in explorer feature

### ISSUE THREAD

**Issue by trihardseven** [demibit/stable-toolkit#16]
When I tried this a few days ago I got annoyed that the images get all randomized inside the folder, making it very hard to find them for posting online (I made thousands of images). So I ended up just using the default store in folder by prompt feature of auto. I haven't tried it since, so if a solution is already in please disregard this.

**Describe the solution you'd like**
I would like an open in explorer feature like auto has. 

**Describe alternatives you've considered**
Not sure, but anything that makes finding the files in explorer easier since randomizing the names makes it all jumbled in explorer. 

**Explain *why* this should be implemented**
What is the point of having a personal booru of your images with automatic tagging if you take 20 minutes to find each image on your PC?

**Comment by demibit** [comment]
Makes sense, will look into this

**Comment by demibit** [comment]
Available as of 2.1.0-luna
