### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by ResleyZ** [demibit/stable-toolkit#17]
**Describe the bug**
Opening 127.0.0.1:8801 only gives a black screen with the text: "Application error: a client-side exception has occurred (see the browser console for more information)."

**Toolkit version**
Which version of the toolkit were you using? 2.7.4

**To Reproduce**
1. Download and run requirements & "download-toolkit.bat"
2. Run "update-toolkit.bat".
3. Run "run-toolkit.bat".
4. Open 127.0.0.1:8801 in Chrome, Edge, Firefox
5. Receive Application error: a client-side exception has occurred (see the browser console for more information).

**Expected behavior**
After deleting and reinstalling the toolkit, being able to view the site again.

**Screenshots**
[Console error](https://imgur.com/a/VKJdUR2)
[127.0.0.1-1667140281237.log](https://github.com/demibit/stable-toolkit/files/9896062/127.0.0.1-1667140281237.log)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Chrome, Edge, Firefox
 - Version: Most up-to-date on all software

**Additional notes**
After being able to access the site once after installation, I could access the settings and image viewer, however, all images were blank/black. I was able to click on them and "open" them, being able to view their information, but the images themselves stayed black. 

After deleting everything, including cache and site data, I've received this error. 
Re-installing the programs specified in Requirements and redownloading stable-toolkit itself has not solved this error.

[127.0.0.1-1667140281237.log](https://github.com/demibit/stable-toolkit/files/9896062/127.0.0.1-1667140281237.log)

**Comment by demibit** [comment]
2.7.4 is the Spring version number. I'd need the version of the service. It should end with "-luna".
You should have a log file called "log.log" in \stable-toolkit\stable-toolkit-back\, could you provide that as well?

**Comment by ResleyZ** [comment]
Heya, sorry for giving the wrong version number! It's at v2.0.3-luna. I've added the log.log as well!

[log.log](https://github.com/demibit/stable-toolkit/files/9896376/log.log)

**Comment by demibit** [comment]
Hmmm, back end seems to have no problems. 
You say you were able to access the site once. Can you recall the exact steps you took, and when the error occurred?

**Comment by ResleyZ** [comment]
Hey, yeah, At first I had trouble reaching the page, which was caused because of my VPN running, then I only got a folder view when going to the page, not exactly sure what fixed it then though.

But once I had it running fine, I was trying some stuff with moving the folders, re-indexing them, and all that stuff, and after a reboot of my PC, and restarting the server, that error showed up. 

I'll try to completey remove everything related to tthe browser, reinstall everything, and then run it again, basically starting from zero. If that doesn't work, I'll also try to install it on my laptop, just to see if it runs fine.

**Comment by demibit** [comment]
What a weird bug... I suppose if you ran the front end via "npm run dev" you could get more information, maybe even the exact line causing the issue, but I am not sure how versed you are with React. You could also try using the 2.1.0 branch as it removes the need for Source/Index folders. I'm also thinking it could potentially be something to with the names of your files as well, since the images are request via an API endpoint from the back-end, there are certain rules for request parameters, I can't recall which, but some special characters are not allowed.

**Comment by ResleyZ** [comment]
> 

I have basically 0 experience with React, but I'm well versed in general PC and IT stuff, so I'll have a look with that.

I will also try the 2.1.0 branch, however, apart from my testing location, which is the regular output folder within the WebUI folder, I do save my images on my other drive, hopefully that won't be a problem with the 2.1.0 version.

Here are some example of my image names, and the folder they are saved in;
C:\Users\quila\AI\Automatic1111\stable-diffusion-webui\outputs\images\txt2img-images
00000-1781807638-Masterpiece, best quality, smooth soft skin, big dreamy eyes, beautiful intricate colored hair, symmetrical, anime wide eyes, so.png
00005-3088987420-(((misaka mikoto))), ((tokiwadai school uniform)), (electrokinesis),  hair clip, hair ornament, medium hair, messy hair, (electr.png
00007-3357074197-(((misaka mikoto))), ((tokiwadai school uniform)), (electrokinesis), (((full body))), hair clip, hair ornament, medium hair, mes.png
00013-4237575599-(((misaka mikoto))), ((tokiwadai school uniform)), (electrokinesis), (((full body))),((adult)), hair clip, hair ornament, medium.png

**Comment by demibit** [comment]
Yeah none of my images have the prompt in them, so maybe some special characters can mess things up. I think different drives shouldn't be problem.

If you cmd into the front end folder, you can do "npm run dev" which runs it in dev mode, generally gives much more descriptive error messages and such. Sorry you have to go through all of this by the way, really not sure why this is happening

**Comment by ResleyZ** [comment]
> Yeah none of my images have the prompt in them, so maybe some special characters can mess things up. I think different drives shouldn't be problem.
> 
> If you cmd into the front end folder, you can do "npm run dev" which runs it in dev mode, generally gives much more descriptive error messages and such. Sorry you have to go through all of this by the way, really not sure why this is happening

Oh no need to apologize!
This is all still a very experimental thing, the main Stable Diffusion stuff, and everything around it, so I would imagine there might be some weird stuff here and there, and I definitely don't mind testing stuff out.

I'll change the names of the images to just stuff like 001, 002, and then boot it again, see what happens. If that doesn't work, I'll try the dev mode stuff, and after that, the 2.1.0 branch.

Also wanted to try some symbolic links / symlink stuff to point resources to another drive, so if everything works and I get around to testing it with symlinks, that might also be interesting :p

**Comment by demibit** [comment]
Stale, closing
