### ISSUE TITLE
[FEATURE]: Is there a way to install as outside a "Extensions"?

### ISSUE THREAD

**Issue by Juan-Cruz-Iturrioz** [demibit/stable-toolkit#18]
I want to know if there is a way to install using the folder "Extensions"

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions

**Comment by demibit** [comment]
There is not, but the Image Browser extension might just be what you're looking for. It's on the page you linked and it seems extremely similar to this.

**Comment by demibit** [comment]
Stale, closing
