### ISSUE TITLE
[BUG]: Images are linked to the wrong location

### ISSUE THREAD

**Issue by davidb0** [demibit/stable-toolkit#19]
**Describe the bug**
Images do not load in the webpage and when inspected points to the wrong file location

**Toolkit version**
v2.7.4

**To Reproduce**
1. Add a directory. eg: E:\ai\old outputs\outputs 3\txt2img-images
2. When the indexation finishes, I see the metadata, prompts, filename, etc, but not the image itself.
3. Right-click, open image in a new tab and see that the image points to:
http://localhost:8800/image?url=E:/ai/old%20outputs/outputs%203/txt2img-images/00009-2350801736.png?imwidth=3840
While in fact, the image is in:
E:\ai\old outputs\outputs 3\txt2img-images\WLOP Michael Garmash ilya kuvshinov krenz kushart Alphonse\00002-2350801729.png

**Expected behavior**
See images, not just metadata.

**Screenshots**
![2022-11-15 08_42_40-](https://user-images.githubusercontent.com/35031448/201936108-8ed8aabf-cd0a-4d18-8db9-fb94b4e1508d.png)
![2022-11-15 08_43_09-Mozilla Firefox](https://user-images.githubusercontent.com/35031448/201936150-f4f2048a-49d2-4074-b887-22e46998c72f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome
 - Version: 106.0.5, 107.0.5304.107

**Additional notes**
I'm using Automatic1111's UI with the option: Create a text file next to every image with generation parameters.

**Comment by demibit** [comment]
This could happen if the images are moved by anything other than the service. Re-indexing images should fix this

**Comment by davidb0** [comment]
> This could happen if the images are moved by anything other than the service. Re-indexing images should fix this

The files are not in the `outputs` folder of my webui. They have been moved as-is to another drive. I have not rearranged the files inside the `outputs` folder.

I can see the images if I add a folder with images, such as `E:\ai\old outputs\outputs 3\txt2img-images\WLOP Michael Garmash ilya kuvshinov krenz kushart Alphonse`. I have thousands of folders with different prompt names though.

**Comment by demibit** [comment]
Is this to say Re-Indexing didn't work? If so, would you mind posting the output of the Spring CMD?

**Comment by demibit** [comment]
Stale, closing
