### ISSUE TITLE
[BUG]: Webui does not display until run-front.bat is manually run

### ISSUE THREAD

**Issue by JTJutajoh** [demibit/stable-toolkit#21]
**Describe the bug**
Upon initial installation of the toolkit, navigating to http://127.0.0.1:8801/ only displays an index page and not the toolkit's UI. Once run-front.bat has been run manually, however, it works. 

**Toolkit version**
v2.1.0-luna

**To Reproduce**
1. Start with a fresh clone of the repository and all dependencies installed
2. Run download-toolkit.bat as instructed by installation instructions and wait for it to complete
3. Navigate to the new stable-toolkit subfolder
4. Run the run-toolkit.bat file
5. Navigate to http://127.0.0.1:8801/ after the server has started
6. Observe an Index page 

**Expected behavior**
Navigating to http://127.0.0.1:8801/ after running run-toolkit.bat as the installation instructions say should display the ui in the browser rather than an Index page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 108.02

**Additional notes**
Running run-front.bat once seems to solve the problem permanently for the installation. It appears to perform an installation step that gets skipped when only running run-toolkit.bat.

**Another possibly related issue with the installation instructions:**
I found that the http-server command prompt complained about the system being unable to find a path until I had manually run update-toolkit.bat after installation. There seems to be another step here missing from the installation instructions.

**Comment by demibit** [comment]
> I had manually run update-toolkit.bat after installation. There seems to be another step here missing from the installation instructions.

Yes, this is correct and is missing from the installation instructions. I will update the readme when I get the chance with this, thank you.

**Comment by demibit** [comment]
Included the `update-toolkit.bat` line in `2.2.0-luna`, closing.
