### ISSUE TITLE
Feature request: match tag blobs

### ISSUE THREAD

**Issue by masonc15** [demibit/stable-toolkit#7]
Is it possible to match images to a partial tag?  An example of this would be:

Prompt: john smith dressed as jane doe, by greg rutkowski, 8k

The tag that I want to match here would be just "john smith", not the entire comma-separated section.  Is this currently possible?  If not, it would be a really nice addition.  Thanks!

**Comment by demibit** [comment]
Did some quick tests, seems like it'll be simple to improve the image tagging, and your exact example gets picked up as you described. Will include this in next release.

**Comment by demibit** [comment]
Closing issue as it's implemented in luna
