### ISSUE TITLE
Suggestion: update guide

### ISSUE THREAD

**Issue by trihardseven** [demibit/stable-toolkit#8]
A how to update guide.

**Comment by demibit** [comment]
Next release will make this project open source, and include a batch file that will update your files with git, and compile the source code, which in turn should update the batch files that'll be run. All automatically, *hopefully...*

For now:
1. Download the official [git bash release](https://git-scm.com/downloads)
2. In the folder you want the toolkit to be in right click -> git bash here
3. Type "git clone https://github.com/demibit/stable-toolkit.git" and press enter. This will download the repo
5. To update you simply 
    - Go into the stable-toolkit folder
    - Right click
    - Open git bash here
    - Type "git pull origin main"
    - Press enter
    - It will tell you if you are up to date, or update your files

**Comment by trihardseven** [comment]
Thanks. I have a question though, how do I change the order of the images shown by default? They tend to be all mixed up instead of being ordered chronologically.

**Comment by demibit** [comment]
No way as of right now, will be doable in the next release

**Comment by demibit** [comment]
Closing as update and installation have been simplified
